apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sql-service-qa
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/amokscience/argo-apps
    targetRevision: main
    path: argocd-apps/sql-service/overlays/qa
  destination:
    server: https://kubernetes.default.svc
    namespace: qa
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
