---
# Source: front-end/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: front-end
spec:
  selector:
    app: front-end
  ports:
  - port: 8040
    targetPort: 8040
    protocol: TCP
    name: http
  type: ClusterIP
---
# Source: front-end/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-end
spec:
  revisionHistoryLimit: 3
  replicas: 3
  selector:
    matchLabels:
      app: front-end
  template:
    metadata:
      labels:
        app: front-end
    spec:
      containers:
      - name: front-end
        image: "amokscience/front-end:latest"
        imagePullPolicy: Always
        ports:
        - containerPort: 8040
          name: http
        env:
        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: front-end-config
              key: environment
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
