apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: aws-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets
    kind: ClusterSecretStore
  target:
    name: aws-credentials
    creationPolicy: Owner
  data:
  - secretKey: AWS_ACCESS_KEY_ID
    remoteRef:
      key: aws-credentials
      property: accessKeyId
  - secretKey: AWS_SECRET_ACCESS_KEY
    remoteRef:
      key: aws-credentials
      property: secretAccessKey
  - secretKey: AWS_REGION
    remoteRef:
      key: aws-credentials
      property: region
