apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infrastructure-eso
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/amokscience/argo-apps
    path: infrastructure/eso
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
