apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sql-service-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/amokscience/argo-apps
    targetRevision: main
    path: sql-service/overlays/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
