# ArgoCD RBAC Configuration
# Managed by ArgoCD after initial bootstrap
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
data:
  scopes: '[groups, email]'
  policy.default: ''
  policy.csv: |
    # Superuser - full admin access
    g, admin, role:admin
    
    # Dev users - access only to devtest project applications
    p, role:devtest-developer, applications, get, devtest/*, allow
    p, role:devtest-developer, applications, sync, devtest/*, allow
    p, role:devtest-developer, applications, override, devtest/*, allow
    p, role:devtest-developer, applications, update, devtest/*, allow
    p, role:devtest-developer, applications, delete, devtest/*, allow
    p, role:devtest-developer, applications, create, devtest/*, allow
    p, role:devtest-developer, logs, get, devtest/*, allow
    p, role:devtest-developer, exec, create, devtest/*, allow
    p, role:devtest-developer, projects, get, devtest, allow
    p, role:devtest-developer, repositories, get, *, allow
    p, role:devtest-developer, clusters, get, *, allow
    g, dev, role:devtest-developer
