apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/amokscience/argo-apps
    targetRevision: main
    path: argocd/applications
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  ignoreDifferences:
  # nginx-ingress Service nodePorts (null vs assigned)
  - group: ""
    kind: Service
    jsonPointers:
    - /spec/ports/0/nodePort
    - /spec/ports/1/nodePort
  # F5 AppProtect CRDs (status/managed fields)
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    jsonPointers:
    - /status
  # Ingress status
  - group: networking.k8s.io
    kind: Ingress
    jsonPointers:
    - /status
  # election
  - group: coordination.k8s.io
    kind: Lease
    jqPathExpressions:
      - .spec
