apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/amokscience/argo-apps
    targetRevision: main
    path: argocd/applications
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  # GLOBAL IGNORES - applies to ALL child apps
  ignoreDifferences:
  # Ignore nodePort drift (nginx-ingress, LoadBalancer services)
  - group: ""
    kind: Service
    jsonPointers:
    - /spec/ports/*/nodePort
  # Ignore Ingress status (loadBalancer, conditions)
  - group: networking.k8s.io
    kind: Ingress
    jsonPointers:
    - /status
  # Ignore Deployment status/replicas drift
  - group: apps
    kind: Deployment
    jsonPointers:
    - /status
  # Ignore Secret data rotation
  - group: ""
    kind: Secret
    jsonPointers:
    - /data
