apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: default  # This updates your existing default project
  namespace: argocd
spec:
  description: Default ArgoCD project
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:  # CRITICAL: Add this
  - group: ''
    kind: Pod
  - group: apps
    kind: ReplicaSet
  - group: ''
    kind: Service
  - group: ''
    kind: Endpoints
  - group: discovery
    kind: EndpointSlice
  destinations:
  - namespace: '*'
    server: 'https://kubernetes.default.svc'
  sourceRepos:
  - '*'
