apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: default
  namespace: argocd  # Replace with your Argo CD namespace
spec:
  description: Default Argo CD project
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: '*'
  namespaceResourceWhitelist:  # Use whitelist (allow list) instead of blacklist
  - group: ''
    kind: ConfigMap
  - group: rbac.authorization.k8s.io
    kind: Role
  - group: rbac.authorization.k8s.io
    kind: RoleBinding
  - group: ''
    kind: ServiceAccount
  - group: ''
    kind: Secret
  - group: apps
    kind: Deployment
  - group: apps
    kind: StatefulSet
  - group: ''
    kind: Service
  - group: external-secrets.io
    kind: SecretStore
  - group: external-secrets.io
    kind: ExternalSecret
  - group: networking.k8s.io
    kind: Ingress    
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
