apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://argoproj.github.io/argo-helm
      chart: argo-cd
      # To upgrade ArgoCD: change this version, commit, and ArgoCD will upgrade itself.
      # Find versions at: https://github.com/argoproj/argo-helm/releases
      targetRevision: 9.4.4
      helm:
        releaseName: argocd
        valueFiles:
          - $values/argocd/helm/values-base.yaml
          - $values/argocd/helm/values-rbac.yaml
          - $values/argocd/helm/values-notifications.yaml
    - repoURL: https://github.com/amokscience/argo-apps
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    - RespectIgnoreDifferences=true
