apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-cd
    # To upgrade ArgoCD: change this version, commit, and ArgoCD will upgrade itself.
    # Find versions at: https://github.com/argoproj/argo-helm/releases
    targetRevision: 9.4.5
    helm:
      releaseName: argocd
      values: |
        configs:
          params:
            # Run server without TLS - terminated at NGINX ingress
            server.insecure: true
          cm:
            timeout.reconciliation: "60s"
            url: "https://argocd.amok"
            oidc.tls.insecure.skip.verify: "true"
            oidc.config: |
              name: Keycloak
              issuer: https://keycloak.amok:8443/realms/master
              clientID: argocd
              clientSecret: $argocd-oidc-keycloak:client-secret
              logoutURL: https://keycloak.amok:8443/realms/master/protocol/openid-connect/logout?client_id=argocd&post_logout_redirect_uri=https://argocd.amok
              requestedScopes: ["openid","profile","email","groups"]
          rbac:
            scopes: '[groups, email]'
            policy.default: ''
            policy.csv: |
              g, admin, role:admin
              p, role:devtest-developer, applications, get, devtest/*, allow
              p, role:devtest-developer, applications, sync, devtest/*, allow
              p, role:devtest-developer, applications, override, devtest/*, allow
              p, role:devtest-developer, applications, update, devtest/*, allow
              p, role:devtest-developer, applications, delete, devtest/*, allow
              p, role:devtest-developer, applications, create, devtest/*, allow
              p, role:devtest-developer, logs, get, devtest/*, allow
              p, role:devtest-developer, exec, create, devtest/*, allow
              p, role:devtest-developer, projects, get, devtest, allow
              p, role:devtest-developer, repositories, get, *, allow
              p, role:devtest-developer, clusters, get, *, allow
              g, dev, role:devtest-developer

        server:
          ingress:
            enabled: true
            ingressClassName: nginx
            annotations:
              # F5 NGINX annotations (nginx.org/* only - nginx.ingress.kubernetes.io/* are ignored)
              nginx.org/proxy-buffering: "false"
              nginx.org/proxy-read-timeout: "3600s"
              nginx.org/proxy-send-timeout: "3600s"
              nginx.org/proxy-connect-timeout: "120s"
            hosts:
            - argocd.amok
            tls:
            - secretName: argocd-tls
              hosts:
              - argocd.amok
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    - RespectIgnoreDifferences=true
