apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 55.0.0
    helm:
      releaseName: kube-prometheus-stack
      values: |
        grafana:
          enabled: true
          adminPassword: admin

          # Sidecar watches all namespaces for ConfigMaps labelled grafana_dashboard: "1"
          # and hot-loads them — already enabled by default in kube-prometheus-stack.
          sidecar:
            dashboards:
              enabled: true
              searchNamespace: ALL

          # Additional dashboard provider folder for dashboards pulled from grafana.com
          dashboardProviders:
            dashboardproviders.yaml:
              apiVersion: 1
              providers:
              - name: custom
                orgId: 1
                folder: Custom
                type: file
                disableDeletion: false
                editable: true
                options:
                  path: /var/lib/grafana/dashboards/custom

          # Dashboards downloaded from grafana.com at Grafana pod startup.
          # gnetId = the numeric ID from the grafana.com/dashboards URL.
          dashboards:
            custom:
              # ArgoCD application/sync/health overview
              argocd-overview:
                gnetId: 14584
                revision: 1
                datasource: Prometheus
              # Kubernetes global cluster view (pods, deployments, no node-exporter required)
              kubernetes-views-global:
                gnetId: 15757
                revision: 37
                datasource: Prometheus
              # Kubernetes namespace detail
              kubernetes-views-namespaces:
                gnetId: 15758
                revision: 34
                datasource: Prometheus
              # Kubernetes pod detail
              kubernetes-views-pods:
                gnetId: 15759
                revision: 29
                datasource: Prometheus

          ingress:
            enabled: true
            ingressClassName: nginx
            annotations:
              nginx.ingress.kubernetes.io/proxy-connect-timeout: "5"
              nginx.ingress.kubernetes.io/proxy-read-timeout: "30"
              nginx.ingress.kubernetes.io/proxy-send-timeout: "30"
              nginx.ingress.kubernetes.io/proxy-next-upstream: "error timeout http_502 http_503 http_504"
              nginx.ingress.kubernetes.io/proxy-next-upstream-tries: "3"
              nginx.ingress.kubernetes.io/proxy-next-upstream-timeout: "15"
              nginx.ingress.kubernetes.io/service-upstream: "true"
              nginx.org/proxy-connect-timeout: "5s"
              nginx.org/proxy-read-timeout: "30s"
              nginx.org/proxy-send-timeout: "30s"
            hosts:
            - grafana.amok
            tls:
            - secretName: grafana-tls
              hosts:
              - grafana.amok
        
        prometheus:
          ingress:
            enabled: true
            ingressClassName: nginx
            annotations:
              nginx.ingress.kubernetes.io/proxy-connect-timeout: "5"
              nginx.ingress.kubernetes.io/proxy-read-timeout: "30"
              nginx.ingress.kubernetes.io/proxy-send-timeout: "30"
              nginx.ingress.kubernetes.io/service-upstream: "true"
            hosts:
            - prometheus.amok
            tls:
            - secretName: prometheus-tls
              hosts:
              - prometheus.amok
          prometheusSpec:
            serviceMonitorSelectorNilUsesHelmValues: false
            podMonitorSelectorNilUsesHelmValues: false
            retention: 7d
            storageSpec:
              volumeClaimTemplate:
                spec:
                  accessModes: ["ReadWriteOnce"]
                  resources:
                    requests:
                      storage: 5Gi
            resources:
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                cpu: 500m
                memory: 512Mi
        
        kubeProxy:
          enabled: false
        kubeScheduler:
          enabled: false
        kubeControllerManager:
          enabled: false
        kubeEtcd:
          enabled: false
        
        nodeExporter:
          enabled: false
        
        prometheusOperator:
          admissionWebhooks:
            enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    - RespectIgnoreDifferences=true
