---
# ArgoCD OIDC Configuration for Keycloak
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  url: https://argocd.local
  oidc.tls.insecure.skip.verify: "true" 
  oidc.config: |
    name: Keycloak
    issuer: https://keycloak.local:8443/realms/master
    clientID: argocd
    clientSecret: $argocd-oidc-keycloak:client-secret
    logoutURL: https://keycloak.local:8443/realms/master/protocol/openid-connect/logout?client_id=argocd&post_logout_redirect_uri=https://argocd.local
    requestedScopes: ["openid","profile","email","groups"]
---
# ArgoCD RBAC Configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
data:
  scopes: '[groups, email]'
  policy.default: 'role:viewer'
  policy.csv: |
    # Grant admin role to argocd-admins group from Keycloak
    g, argocd-admins, role:admin
    # Grant read-only to argocd-viewers group
    g, argocd-viewers, role:viewer
---
# Ensure server.insecure is set
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cmd-params-cm
  namespace: argocd
data:
  server.insecure: 'true'
