---
# ArgoCD OIDC Configuration for Keycloak
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  oidc.config: |
    name: Keycloak
    issuer: https://keycloak.local:8443/realms/master
    clientID: argocd
    clientSecret: 8GZB5E2TGQeJdOOcSFRQz9KdY2BVGxwn
    requestedScopes:
      - openid
      - profile
      - email
      - groups
    requestedIDTokenClaims:
      groups:
        essential: true
    rootCA: |
      -----BEGIN CERTIFICATE-----
      MIIE1zCCAz+gAwIBAgIQeWldHIl5n69GtEWvEaSK+jANBgkqhkiG9w0BAQsFADCB
      gzEeMBwGA1UEChMVbWtjZXJ0IGRldmVsb3BtZW50IENBMSwwKgYDVQQLDCNERVNL
      VE9QLUlOS0hNUFBcS2VuQERFU0tUT1AtSU5LSE1QUDEzMDEGA1UEAwwqbWtjZXJ0
      IERFU0tUT1AtSU5LSE1QUFxLZW5AREVTS1RPUC1JTktITVBQMB4XDTI2MDIwNzIw
      NTUxOVoXDTM2MDIwNzIwNTUxOVowgYMxHjAcBgNVBAoTFW1rY2VydCBkZXZlbG9w
      bWVudCBDQTEsMCoGA1UECwwjREVTS1RPUC1JTktITVBQXEtlbkBERVNLVE9QLUlO
      S0hNUFAxMzAxBgNVBAMMKm1rY2VydCBERVNLVE9QLUlOS0hNUFBcS2VuQERFU0tU
      T1AtSU5LSE1QUDCCAaIwDQYJKoZIhvcNAQEBBQADggGPADCCAYoCggGBAJnVcWa/
      4JbeUNk63Q+OypGi62gQ+uUxp3lpoeQOUWHZsmUc09/MhPOL9gznFWcv7waYxk+9
      ASbeBtTZA3BSPfFZ50gM7gb8Kc0qQ1AA28B3yGSMhr0TAxVvF/aawiOQvhI80Nsb
      OCohYc+MjnuYBBjH/Jbj6sG9YJq6O9iTBAdbWNWEfLql55n9cRLWvALo0Y9bulNs
      YsCcHW8vUUpkT/+Arr+a8l9uLE4rhwn+yLEwMirAuQXUrRo1/TKGClA15U6vSKx0
      90ofWEyXrfdNyiQvrUG9wVfvfyX0fsSKJx0psMyMuXkF5XFWiPB5wYbSTiIpRv5a
      49P1F/Eb4MO886Vt4WCRrbQLmjb+t/zaVc1WR7QowzUUPstP6EAQckPDtjVDJKlo
      eKGN8DySbJ1ZgmKyolVlt3g/gAYEga+bBe7MthkIIfyrC3k1isG+XKfY38mJlizL
      /HRy2EiVQiTz+jIcLkrVsa6+nNEAstP/QTSyAk/IusFML1QbPEZ8XAdZ0wIDAQAB
      o0UwQzAOBgNVHQ8BAf8EBAMCAgQwEgYDVR0TAQH/BAgwBgEB/wIBADAdBgNVHQ4E
      FgQU4DxIyMbNQJp8KP6G4fTlo3E6lqEwDQYJKoZIhvcNAQELBQADggGBAIGRiZQF
      YZs7mGOPcy0DxLSXRrDBPo/+agD5GvjBhc+A5/epQEHv76t6w7miD7hFqcJDPmWL
      R8s+1uhDEAgYwmqiG/2/QbTtVdmkhYyn0VN5q/Czmtc88FbpNiweZArcvHA3HO6Q
      493g8G17xbO3AmLFRxzZiNZlyoIlQ+a2YNLaIHZLbWnfYafF+NEYKEt7zxSVIQ9o
      PsvUVtoXHWymGq5NfY4Szl29/G4UjtyUupE1nWtX+mO+QZ1di34+W4kr87xBv1Oy
      ZGFjyVUR3DFYM1tUviRHA8ngeUT2joj0VnNF/5DOvZh7WT5bGLDe25mxvWQZuiBe
      TnMRYz9ZwBxt+BVLkRK24o4hmdSsjKGT55dc5A1WRW8WFP+IL6uOpnJpj7SZoU69
      BEx6nZoDPA8T4+Pv14R4DbukZUlMaegNVF7Q+HQsTNgxQRbrXKBDRlDDWFBLPqNS
      IkeQLyh47d69M6nW4S/cm2v/Gp7lpnln59ggBuQGiPxBtIJQwuP0UcUHQg==
      -----END CERTIFICATE-----
---
# ArgoCD RBAC Configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
data:
  scopes: '[groups, email]'
  policy.default: 'role:viewer'
  policy.csv: |
    # Grant admin role to argocd-admins group from Keycloak
    g, argocd-admins, role:admin
    # Grant read-only to argocd-viewers group
    g, argocd-viewers, role:viewer
---
# Ensure server.insecure is set
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cmd-params-cm
  namespace: argocd
data:
  server.insecure: 'true'
