apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-keycloak-oidc
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
  - repoURL: https://github.com/amokscience/argo-apps
    targetRevision: main
    path: argocd/applications
    include: argocd-keycloak-oidc.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  syncOptions:
  - RespectIgnoreDifferences=true
