apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: counting-dev
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: devtest
  source:
    repoURL: https://github.com/amokscience/argo-apps
    targetRevision: main
    path: counting/helm
    helm:
      valueFiles:
      - values-dev.yaml
  
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
  
  # Ignore certain resource differences
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas
