apiVersion: v1
kind: Namespace
metadata:
  name: nginx-gateway
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-gateway-fabric
  namespace: argocd
spec:
  project: default
  source:
    chart: nginx-gateway
    repoURL: https://helm.nginx.com/stable
    targetRevision: 1.3.0  # Pin to specific version
    helm:
      releaseName: nginx-gateway
      values: |
        service:
          type: LoadBalancer
          # For local dev, you can use NodePort instead
          # type: NodePort
        # Gateway configuration
        gateway:
          enabled: true
          name: argocd-gateway
          namespace: argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx-gateway
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
