apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: example-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets
    kind: SecretStore
  target:
    name: my-kubernetes-secret
    creationPolicy: Owner
  data:
  - secretKey: username
    remoteRef:
      key: my-app-credentials  # AWS Secrets Manager secret name
      property: username       # JSON property name
  - secretKey: password
    remoteRef:
      key: my-app-credentials
      property: password
