apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: aws-secrets
  namespace: external-secrets
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-west-2
      auth:
        secretRef:
          accessKey:
            name: aws-credentials
            key: access-key
          secretKey:
            name: aws-credentials
            key: secret-access-key
